import UserPackage from "../models/UserPackage.js";
import Earning from "../models/Earning.js";
import User from "../models/User.js";
import PlatformSettings from "../models/PlatformSettings.js";
import DailyPnl from "../models/DailyPnl.js";

/**
 * Distributes one platform calendar day's REAL trading result.
 *
 * DAILY PROFIT RULES
 * ------------------
 * 1. A package starts earning from the platform day after activation.
 *
 * 2. Gross daily profit for a package:
 *
 *      package price × (platform P&L / 100)
 *
 *    Example:
 *
 *      $108.99 × 10% = $10.899
 *
 * 3. Investor receives their configured share of that gross profit.
 *
 *      gross daily profit × investor share rate
 *
 *    Example at 70%:
 *
 *      $10.899 × 70% = $7.6293
 *
 * 4. Package-specific investorShareOverride is preserved.
 *    If a package has an override, that rate is used instead of
 *    PlatformSettings.investorShareRate.
 *
 * 5. Referral bonus is calculated from the DOWNLINE'S FULL GROSS
 *    DAILY PROFIT, before the investor share is applied.
 *
 *      downline gross daily profit × referralShareRate
 *
 *    Example:
 *
 *      $108.99 × 10% = $10.899
 *      $10.899 × 20% = $2.1798 referral bonus
 *
 * 6. Referral bonuses are only paid on positive P&L days.
 *
 * 7. A referral bonus is only paid when the downline actually
 *    receives daily P&L for that date.
 *
 * 8. Negative P&L days:
 *    - Investor earnings can be negative.
 *    - Referral bonuses are never negative.
 *
 * @param {string} dateStr - Platform calendar date "YYYY-MM-DD"
 * @param {number} pnlPercent - Real admin-reported platform result
 * @param {string} adminId - Admin user ID who entered the P&L
 */
export async function processDailyPnl(dateStr, pnlPercent, adminId) {
  const record = await DailyPnl.findOne({ date: dateStr });

  if (record?.processed) {
    throw new Error(`${dateStr} has already been processed`);
  }

  const settings = await PlatformSettings.getSettings();

  const now = new Date();

  const investorShareRate = Number(settings.investorShareRate ?? 70);
  const referralShareRate = Number(settings.referralShareRate ?? 20);
  const platformPnl = Number(pnlPercent);

  if (!Number.isFinite(platformPnl)) {
    throw new Error("Invalid P&L percentage");
  }

  // ------------------------------------------------------------
  // 1. Expire packages whose earning period has ended.
  // ------------------------------------------------------------

  const allActive = await UserPackage.find({
    status: "active"
  });

  for (const up of allActive) {
    if (up.endDate && up.endDate.getTime() <= now.getTime()) {
      up.status = "expired";
      await up.save();
    }
  }

  // ------------------------------------------------------------
  // 2. Find packages eligible for today's P&L.
  // ------------------------------------------------------------

  const candidates = await UserPackage.find({
    status: "active",
    startDate: { $lte: now },
    creditedDates: { $ne: dateStr }
  });

  let investorsCredited = 0;
  let totalInvestorPayout = 0;

  /*
   * Stores the FULL gross daily profit generated by each downline user.
   *
   * Example:
   *
   * User 2 has $108.99
   * Today's P&L = 10%
   *
   * gross profit = $10.899
   *
   * This is what referral bonus uses.
   *
   * userId -> gross daily profit
   */
  const grossProfitByUser = new Map();

  /*
   * Stores the investor amount actually credited to each user.
   *
   * userId -> investor payout
   *
   * This is useful for tracking and makes the distinction between
   * gross profit and investor payout explicit.
   */
  const investorPayoutByUser = new Map();

  // ------------------------------------------------------------
  // 3. Calculate each active package's daily profit.
  // ------------------------------------------------------------

  for (const up of candidates) {
    const principal = Number(up.pricePaid || 0);

    if (!Number.isFinite(principal) || principal <= 0) {
      continue;
    }

    /*
     * Preserve package-specific investorShareOverride.
     *
     * If override exists:
     *     use package override
     *
     * Otherwise:
     *     use platform investorShareRate
     */
    const shareRate =
      up.investorShareRate !== null &&
      up.investorShareRate !== undefined
        ? Number(up.investorShareRate)
        : investorShareRate;

    /*
     * FULL daily profit generated by this package.
     *
     * Example:
     *
     * $108.99 × 10% = $10.899
     */
    const grossDailyProfit = +(
      principal *
      (platformPnl / 100)
    ).toFixed(4);

    /*
     * Amount actually credited to the investor.
     *
     * Example:
     *
     * $10.899 × 70% = $7.6293
     */
    const investorAmount = +(
      grossDailyProfit *
      (shareRate / 100)
    ).toFixed(4);

    // ----------------------------------------------------------
    // Create investor earning record.
    // ----------------------------------------------------------

    await Earning.create({
      user: up.user,
      userPackage: up._id,
      amount: investorAmount,
      type: "Daily P&L",
      pnlDate: dateStr,
      note:
        `${platformPnl >= 0 ? "Profit" : "Loss"} share: ` +
        `${shareRate}% investor share of ${platformPnl}% platform P&L`
    });

    // ----------------------------------------------------------
    // Credit investor balance.
    // ----------------------------------------------------------

    await User.findByIdAndUpdate(up.user, {
      $inc: {
        availableBalance: investorAmount,
        totalEarnings: investorAmount
      }
    });

    // ----------------------------------------------------------
    // Update package earning history.
    // ----------------------------------------------------------

    up.totalCredited = +(
      Number(up.totalCredited || 0) + investorAmount
    ).toFixed(4);

    up.daysCredited = Number(up.daysCredited || 0) + 1;

    if (!Array.isArray(up.creditedDates)) {
      up.creditedDates = [];
    }

    up.creditedDates.push(dateStr);

    await up.save();

    investorsCredited++;

    totalInvestorPayout += investorAmount;

    // ----------------------------------------------------------
    // Track FULL gross profit for referral calculation.
    //
    // IMPORTANT:
    // This is NOT investorAmount.
    //
    // Referral is based on the downline's total daily profit
    // BEFORE the investor's 70% share is applied.
    // ----------------------------------------------------------

    const userKey = String(up.user);

    grossProfitByUser.set(
      userKey,
      (grossProfitByUser.get(userKey) || 0) + grossDailyProfit
    );

    investorPayoutByUser.set(
      userKey,
      (investorPayoutByUser.get(userKey) || 0) + investorAmount
    );
  }

  // ------------------------------------------------------------
  // 4. Referral bonuses.
  // ------------------------------------------------------------

  let referralsCredited = 0;
  let totalReferralPayout = 0;

  /*
   * Referral bonuses only happen on positive P&L days.
   *
   * Example:
   *
   * Downline gross daily profit = $10.899
   * Referral rate = 20%
   *
   * Bonus = $10.899 × 20%
   *       = $2.1798
   */
  if (platformPnl > 0 && grossProfitByUser.size > 0) {
    const downlineUserIds = [
      ...grossProfitByUser.keys()
    ];

    const downlineUsers = await User.find({
      _id: { $in: downlineUserIds },
      referredBy: { $ne: null }
    }).select("_id referredBy name");

    for (const downline of downlineUsers) {
      const downlineGrossProfit =
        Number(grossProfitByUser.get(String(downline._id))) || 0;

      if (downlineGrossProfit <= 0) {
        continue;
      }

      /*
       * Referral bonus is based on the DOWNLINE'S FULL PROFIT.
       *
       * NOT:
       *
       *   downline investor payout × 20%
       *
       * Instead:
       *
       *   downline gross profit × 20%
       */
      const bonus = +(
        downlineGrossProfit *
        (referralShareRate / 100)
      ).toFixed(4);

      if (bonus <= 0) {
        continue;
      }

      // --------------------------------------------------------
      // Create referral earning record.
      // --------------------------------------------------------

      await Earning.create({
        user: downline.referredBy,
        amount: bonus,
        type: "Referral Bonus",
        pnlDate: dateStr,
        note:
          `Referral bonus: ${referralShareRate}% of ` +
          `${downline.name}'s gross daily profit of $${downlineGrossProfit.toFixed(4)}`
      });

      // --------------------------------------------------------
      // Credit referrer's balance.
      // --------------------------------------------------------

      await User.findByIdAndUpdate(downline.referredBy, {
        $inc: {
          availableBalance: bonus,
          totalEarnings: bonus,
          referralEarnings: bonus
        }
      });

      referralsCredited++;

      totalReferralPayout += bonus;
    }
  }

  // ------------------------------------------------------------
  // 5. Round final totals.
  // ------------------------------------------------------------

  totalInvestorPayout = +totalInvestorPayout.toFixed(4);
  totalReferralPayout = +totalReferralPayout.toFixed(4);

  // ------------------------------------------------------------
  // 6. Mark the platform day as processed.
  // ------------------------------------------------------------

  await DailyPnl.findOneAndUpdate(
    { date: dateStr },
    {
      date: dateStr,
      pnlPercent: platformPnl,
      processed: true,
      createdBy: adminId,
      investorsCredited,
      referralsCredited,
      totalInvestorPayout,
      totalReferralPayout
    },
    {
      upsert: true,
      new: true
    }
  );

  return {
    investorsCredited,
    referralsCredited,
    totalInvestorPayout,
    totalReferralPayout
  };
}