// Common country dial codes for the registration phone dropdown.
// Not exhaustive, but covers the large majority of users.
const countryCodes = [
  { name: "Pakistan", iso: "PK", code: "+92" },
  { name: "United States", iso: "US", code: "+1" },
  { name: "United Kingdom", iso: "GB", code: "+44" },
  { name: "India", iso: "IN", code: "+91" },
  { name: "United Arab Emirates", iso: "AE", code: "+971" },
  { name: "Saudi Arabia", iso: "SA", code: "+966" },
  { name: "Bangladesh", iso: "BD", code: "+880" },
  { name: "Canada", iso: "CA", code: "+1" },
  { name: "Australia", iso: "AU", code: "+61" },
  { name: "Germany", iso: "DE", code: "+49" },
  { name: "France", iso: "FR", code: "+33" },
  { name: "Nigeria", iso: "NG", code: "+234" },
  { name: "Turkey", iso: "TR", code: "+90" },
  { name: "Indonesia", iso: "ID", code: "+62" },
  { name: "Philippines", iso: "PH", code: "+63" },
  { name: "China", iso: "CN", code: "+86" },
  { name: "Brazil", iso: "BR", code: "+55" },
  { name: "South Africa", iso: "ZA", code: "+27" },
  { name: "Egypt", iso: "EG", code: "+20" },
  { name: "Malaysia", iso: "MY", code: "+60" },
  { name: "Singapore", iso: "SG", code: "+65" },
  { name: "Kenya", iso: "KE", code: "+254" },
  { name: "Qatar", iso: "QA", code: "+974" },
  { name: "Kuwait", iso: "KW", code: "+965" },
  { name: "Oman", iso: "OM", code: "+968" },
  { name: "Bahrain", iso: "BH", code: "+973" },
  { name: "Sri Lanka", iso: "LK", code: "+94" },
  { name: "Nepal", iso: "NP", code: "+977" },
  { name: "Netherlands", iso: "NL", code: "+31" },
  { name: "Spain", iso: "ES", code: "+34" },
  { name: "Italy", iso: "IT", code: "+39" },
  { name: "Russia", iso: "RU", code: "+7" },
  { name: "Japan", iso: "JP", code: "+81" },
  { name: "South Korea", iso: "KR", code: "+82" }
];

export default countryCodes;
